services:
  keycloak:
    image: "keycloak/http:23.0.6"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: start-dev

  web:
    environment:
      - PORT=8501
      - KC_SERVER=keycloak
      - KC_PORT=8080
      - KC_CLIENT_ID=userclient
      - KC_REALM=userrealm
      - KC_SECRET_KEY=T173C1G9fWviL36t1WCvl55klaBy4Jlv
      - HM_SERVER=localhost
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - keycloak
  